dist: xenial
language: python

services:
  - redis-server
  - mysql
  - docker

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install codecov

script:
  - pytest --cov=./hermes ./tests

after_success:
  - codecov

deploy:
  - provider: script
    script: bash ./docker-deploy.sh master
    on:
      branch: master

  - provider: script
    script: bash ./docker-deploy.sh dev
    on:
      branch: dev

notifications:
  slack:
    secure: W/1DnXH/cJUm3wyu6uQRp8pQFi3vN6h5FgHapaKP2RwOqHqIg+FWGCRRIHEcg8stpf296grD1kbs0ipDjuV5uUXwZ0p/HKsdR6gIFzod3LzEQUNg5sLqjIEDqkIZCA2UJIZPX5RcEzYL6Mkp6Lvbi1/hL+PE8guVVVl7r5/xZ0TRd6jK8pY5unYeCjURjOiHr/GvP4RDici7UwbgYMo0tCOKTe5LT03nVO8+NUeyRoQDQApaf6zpKmdtBaJb3V+GfIAnvEXYI0yGN3T8xLiKKRvzFPLGIV4fN29SwUOTP3hmwDj0XN+F0QfipmNiJQ7oX+hwWxR4wV24KTkFGA/fBn7VC+HOeRrt9gu0hW6t/XBWzyVlW/6Nz7yRJ1iKcub75OhZ+rqC04ni2FJJeef+B/9sH/9MKvQzadneHpyaCtn+8bB9DqY3gXQv9R14lXLHKHakg+R0ACcidTDzOLrDyfKnFjp+pGAudYYD5liGFCJHJc00D3Obx7osU/An5rxOYkYosmrYwCIQ4qb9RvJWFfD3QjHf+x1CHQJbRWDVJaUJ5BK6CwTBnNDSb9g7vBpJWTL0d1VTiT+5JdpCMCbxtT5iQc5gwDSr1EkGr+ZMCQuxxx/qqW/VVv6DE1vA7CPg6EPZFOiMjpamM7cDaJwOskXJUywWcQpNQUIsmhx1cqg=
