dist: xenial
language: python

services:
  - redis-server
  - mysql

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install codecov

script:
  - pytest --cov=./hermes ./tests

after_success:
  - codecov




